### ISSUE TITLE
How to mine?

### ISSUE THREAD

**Issue by aixwu** [elastos/Elastos.ELA#1]
SeedList just only 127.0.0.1 ???

**Comment by yz89** [comment]
No need. Just open the "AutoMining" config option.

**Comment by Jianfree** [comment]
@AixWu Did you mine successfully?

**Comment by AixWu** [comment]
@Jianfree no, it didn't connect any node, and it seems just only one node on this chain, please access 
 https://blockchain.elastos.org/status
Just funny!

**Comment by Jianfree** [comment]
@AixWu me too. it runs just as  a local node。

**Comment by Jianfree** [comment]
@yz89 can you tell me how to  mine successfully  ? thanks .

**Comment by yushunan** [comment]
ELA has a command line tool for creating the wallet, transferring account and  manual mining , experience the ELA node functions need to be combined with this tool, this command line tool will open source soon.
ELA node has three running modes, respectively is MainNet, TestNet and RegNet. You can start node use RegNet mode, and use the command line tool to perform manual mining to familiar with the functions of ELA.Command line tool will provide instructions after open source, stay tuned :-)

**Comment by Jianfree** [comment]
@yushunan thank you . i am looking forward it .

**Comment by luozhaohui** [comment]
Is there any docs about how to mine on MainNet? Or a default config.json  with seed for MainNet?

**Comment by yz89** [comment]
There are merged mining interfaces https://github.com/elastos/Elastos.ELA/blob/release_v0.2.1/docs/jsonrpc_apis.md#createauxblock.
