### ISSUE TITLE
how to set the path of Chain

### ISSUE THREAD

**Issue by bitcodernull** [elastos/Elastos.ELA#12]
i install the node on system device
i want to set the Chain data on other device
how to config it

**Comment by kevingzhang** [comment]
I did not quite understand your question. Are you saying you want to save all the block data into another folder?
If you do not want to save the block data, why do not you use a light wallet instead of full node?

**Comment by bitcodernull** [comment]
yes , i want to save block data into another folder


i have solved it by soft link 
thanks
