### ISSUE TITLE
connect testnet error

### ISSUE THREAD

**Issue by wshhz** [elastos/Elastos.ELA#1200]
This is my config.json
{
  "Configuration": {
    "ActiveNet": "testnet",
    "PowConfiguration": {
      "PayToAddr": "8ZNizBf4KhhPjeJRGpox6rPcHE5Np6tFx3",
      "MinerInfo": "ELA",
      "MinTxFee": 100
    },
    "HttpRestPort": 21334,
    "HttpRestStart": true,
    "EnableRPC": true,
    "RpcConfiguration": {
      "User": "User",
      "Pass": "Password",
      "WhiteIPList": [
        "127.0.0.1"
      ]
    }
  }
}

This is print:
2019/09/05 14:38:24.817225 [INF] GID 1, Node version: v0.3.7-3-g2c62
2019/09/05 14:38:24.817581 [INF] GID 1, go version go1.12.7 linux/amd64
2019/09/05 14:38:25.354112 [INF] GID 1, current block height -> 0
2019/09/05 14:38:25.354273 [WRN] GID 33, recover form check points fail:  can't find dpos store object
2019/09/05 14:38:25.354510 [INF] GID 33, [RecoverFromCheckPoints] recover start height:  200000
2019/09/05 14:38:25.354708 [INF] GID 1, Start the P2P networks
2019/09/05 14:38:25.354797 [INF] GID 1, Start services
2019/09/05 14:38:30.355241 [INF] GID 1, Start consensus
2019-09-05 14:39:25.355 [INF] STAT: -> 0 []
2019-09-05 14:40:25.355 [INF] STAT: -> 0 []

How do I connect to the test network?

**Comment by kpachhai** [comment]
Use the following config file:
I don't think you need all those config parameters. The following config works for me fine.
 
{
  "Configuration": {
    "ActiveNet": "testnet",
    "DPoSConfiguration": {
      "EnableArbiter": false,
      "IPAddress": "127.0.0.1"
    },
    "HttpRestStart": true,
    "EnableRPC": true,
    "RpcConfiguration": {
      "User": "User",
      "Pass": "Password",
      "WhiteIPList": [
        "127.0.0.1"
      ]
    }
  }
}

**Comment by wshhz** [comment]
I used the configuration you gave, but the result is as follows:
2019/09/06 10:57:11.393512 [INF] GID 1, Node version: v0.3.7-3-g2c62
2019/09/06 10:57:11.393959 [INF] GID 1, go version go1.12.7 linux/amd64
2019/09/06 10:57:11.547429 [INF] GID 1, current block height -> 0
2019/09/06 10:57:11.547539 [WRN] GID 13, recover form check points fail:  can't find dpos store object
2019/09/06 10:57:11.547618 [INF] GID 13, [RecoverFromCheckPoints] recover start height:  200000
2019/09/06 10:57:11.547764 [INF] GID 1, Start the P2P networks
2019/09/06 10:57:11.547843 [INF] GID 1, Start services
2019/09/06 10:57:16.548390 [INF] GID 1, Start consensus
2019-09-06 10:58:11.548 [INF] STAT: -> 0 []
@kpachhai

**Comment by kpachhai** [comment]
What version of ela node are you using? Also, you can check whether or not your node is running by checking its height. I would do that to verify.

**Comment by wshhz** [comment]
I compiled it with master branch code. The height of the block is 0.

**Comment by kpachhai** [comment]
master branch is not always the best branch to use because chances are it's not very stable. Use one of the stable releases. Use tag v0.3.7 to compile your code

**Comment by wshhz** [comment]
I used the code of tag v0.3.7, but I still can't connect.The print also:
2019/09/06 11:33:09.477054 [INF] GID 1, Node version: v0.3.7
2019/09/06 11:33:09.477598 [INF] GID 1, go version go1.12.7 linux/amd64
2019/09/06 11:33:09.799259 [INF] GID 1, current block height -> 0
2019/09/06 11:33:09.799476 [WRN] GID 6, recover form check points fail:  can't find dpos store object
2019/09/06 11:33:09.799581 [INF] GID 6, [RecoverFromCheckPoints] recover start height:  200000
2019/09/06 11:33:09.799875 [INF] GID 1, Start the P2P networks
2019/09/06 11:33:09.799996 [INF] GID 1, Start services
2019/09/06 11:33:14.800722 [INF] GID 1, Start consensus
2019-09-06 11:34:09.800 [INF] STAT: -> 0 []
@kpachhai

**Comment by wshhz** [comment]
Is your node having a problem? The main network node can run normally.

**Comment by kpachhai** [comment]
The only thing I can think of is the testnet may be undergoing some kind of maintenance. In the future, there will be a website that will list the status of testnet but maybe you can try this again tomorrow. If that doesn't work, maybe @bocheng0000 can help

**Comment by wshhz** [comment]
Can you solve it quickly? I need to test on the test network.

**Comment by wshhz** [comment]
How long can your test network be done? I need to access the transfer transaction, the main network can not be tested. @bocheng0000

**Comment by wshhz** [comment]
Also, what is the address of your test network block browser? @kpachhai

**Comment by kpachhai** [comment]
https://blockchain-beta.elastos.org/

**Comment by wshhz** [comment]
The testnet is still unable to synchronize the nodes. Can someone solve this problem?
