### ISSUE TITLE
 When I transfer money, how do I calculate the fee I am dealing with?

### ISSUE THREAD

**Issue by wshhz** [elastos/Elastos.ELA#1210]
I need to calculate a minimum available fee.
How can I calculate?

**Comment by kpachhai** [comment]
https://github.com/elastos/Elastos.ELA/blob/master/docs/jsonrpc_apis.md#estimatesmartfee

**Comment by wshhz** [comment]
Can I always use 0.000001?

**Comment by kpachhai** [comment]
You could but it all depends on whether miners will accept your transaction. In times when there's high volume of transactions, miners may decide to not accept your transaction if it's too low but you can try using that number if you so choose.

**Comment by wshhz** [comment]
I understand,tks.
