### ISSUE TITLE
how to start sync block

### ISSUE THREAD

**Issue by bitcodernull** [elastos/Elastos.ELA#13]
I have Compiled and deployed the node 
then i run ./node , it does not start to sync block

the logs:
2018/03/28 19:08:23.226005 [TRACE] GID 29, func1() main.go:44 BlockHeight =  0
2018/03/28 19:08:23.226054 [TRACE] GID 29, DumpState() blockchain.go:1011 bc.BestChain= 8d7014f2f941caa1972c8033b2f0a860ec8d4938b12bae2c62512852a558f405
2018/03/28 19:08:23.226089 [TRACE] GID 29, DumpState() blockchain.go:1020 bc.Root= 8d7014f2f941caa1972c8033b2f0a860ec8d4938b12bae2c62512852a558f405
2018/03/28 19:08:23.226112 [INFO ] GID 29, [ 1 0 0 ]
2018/03/28 19:08:29.190376 [INFO ] GID 28, nbr heigh--> [] 0
2018/03/28 19:08:29.190432 [INFO ] GID 28, needSync:  false
2018/03/28 19:08:29.226269 [TRACE] GID 29, func1() main.go:44 BlockHeight =  0
2018/03/28 19:08:29.226312 [TRACE] GID 29, DumpState() blockchain.go:1011 bc.BestChain= 8d7014f2f941caa1972c8033b2f0a860ec8d4938b12bae2c62512852a558f405
2018/03/28 19:08:29.226368 [TRACE] GID 29, DumpState() blockchain.go:1020 bc.Root= 8d7014f2f941caa1972c8033b2f0a860ec8d4938b12bae2c62512852a558f405
2018/03/28 19:08:29.226388 [INFO ] GID 29, [ 1 0 0 ]

**Comment by bocheng0000** [comment]
The node didn't connect to any other nodes, so it didn't start to sync block. 

> 2018/03/28 19:08:29.190376 [INFO ] GID 28, nbr heigh--> [] 0

shows the node has none neighbor node as the list[] is empty.

If you wanna run the nodes locally, You need to modify the SeedList in config.json.
Here is  the [documentation](./docs/config.json.md) about config.json
I think to deploy more then 4 nodes locally is better.
By the way you need to set one miner node at least.

**Comment by bitcodernull** [comment]
i want to run it to connect mainnet
where i can get seed list of mainnet

**Comment by kevingzhang** [comment]
Currently, the mainnet is not open to public yet. We are going to start testnet shortly, then main net.

**Comment by bitcodernull** [comment]
thanks

**Comment by yz89** [comment]
@bitcodernull  https://github.com/elastos/Elastos.ELA/issues/68#issuecomment-420902091
