### ISSUE TITLE
Is it possible to run an ELA node via TOR ?

### ISSUE THREAD

**Issue by ademcan** [elastos/Elastos.ELA#1559]
To properly run a node one needs to open a list of ports, the most important ones being: 20338 and 20339. I was wondering if it could be possible to run a node via TOR so there is no need to open these ports. I know how to run a TOR service on a specific port but I guess to make it work ELA should also support such an option, correct me if I am wrong (something similar to what is available on the bitcoin.conf file for a Bitcoin node)

source: https://en.bitcoin.it/wiki/Setting_up_a_Tor_hidden_service

**Comment by RainFallsSilent** [comment]
At present we do not support Tor.
