### ISSUE TITLE
How to generate CRAssetsAddress and  CRCExpensesAddress prefix address？

### ISSUE THREAD

**Issue by bxlkm1** [elastos/Elastos.ELA#1634]
hi everyone：

please，How to generate these prefix addresses in the source code？

CRAssetsAddress indicates the "CRASSETSXXXXXXXXXXXXXXXXXXXX2qDX5J"

CRCExpensesAddress indicates the "CREXPENSESXXXXXXXXXXXXXXXXXX4UdT6b"

DestroyELAAddress "ELANULLXXXXXXXXXXXXXXXXXXXXXYvs3rr"

**Comment by peterwillcn** [comment]
> hi everyone：
> 
> please，How to generate these prefix addresses in the source code？
> 
> CRAssetsAddress indicates the "CRASSETSXXXXXXXXXXXXXXXXXXXX2qDX5J"
> 
> CRCExpensesAddress indicates the "CREXPENSESXXXXXXXXXXXXXXXXXX4UdT6b"
> 
> DestroyELAAddress "ELANULLXXXXXXXXXXXXXXXXXXXXXYvs3rr"
```
	decoded, err := base58.BitcoinEncoding.Decode([]byte(address))
	if err != nil {
		fmt.Println(err)
	}

	x, _ := new(big.Int).SetString(string(decoded), 10)
	programHash, err := Uint168FromBytes(x.Bytes()[0:21])
	if err != nil {
		fmt.Println(err)
	}

	addr, err := ToAddress(*programHash)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(addr)
	if addr != address {
		fmt.Println("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
	} else {
		fmt.Println(addr)
	}
```
