### ISSUE TITLE
UI cut off on Unconfirmed Transaction on Block Explorer

### ISSUE THREAD

**Issue by voyage11** [elastos/Elastos.ELA#169]
Please see the screen shot:-

![unconfirmedtransaction](https://user-images.githubusercontent.com/1943839/41707596-0edaec36-7571-11e8-8947-42bc21437ea9.png)

**Comment by free1** [comment]
hi, please provide a link to screen shot, i find this button only have "UNCONFIRMED".

**Comment by xuliting** [comment]
Evaluated

**Comment by voyage11** [comment]
Hi, to make thing easier and faster, I purposely record a video just to show you the issue. Please download and watch it.
[https://github.com/voyage11/VotingSmartContract/blob/master/Transactions.mov](url)

**Comment by free1** [comment]
Thank you for your issues, this question may be the i18n file specific situation only show key, i will update this key and value consistent in next version. thanks :)
