### ISSUE TITLE
Question on Transferring of ELA between 2 wallets

### ISSUE THREAD

**Issue by voyage11** [elastos/Elastos.ELA#176]
I have 2 different Elastos Wallets. A few weeks ago, I was doing a test to transfer 1 ELA from Wallet A to Wallet B.

After transferring, I found out that the total transferring out was 1.995 ELA. Initially, I thought I typed the wrong digit. But, it was not. The final balance on Wallet A is still correct but, the additional 0.995  ELA was transferring to another address of Wallet A.

Example (Fee excluded for simplicity):
Before Transferring:-
Wallet A Address 1: 10 ELA
Wallet B Address 1: 0 ELA

After Transferring:-
Wallet A Address 1: 8.005 ELA
Wallet A Address 2: 0.995 ELA
Wallet A total: 9 ELA

Wallet B Address 1: 1 ELA

May I know what is the reason behind the transferring to its 2nd address on Wallet A?

**Comment by yushunan** [comment]
Our official wallet is a HD wallet, that means you could have many addresses in a wallet. In a transfer transaction, change will be send to a new address.

**Comment by voyage11** [comment]
I read a bit related to HD Wallet from: https://coinsutra.com/hd-wallets-deterministic-wallet/

It still does not explain why I have to send some ELA to another Address of my own wallet. To have better privacy? So that other people will not know exactly how much ELA that I have in my wallet? Since people will not know if that address is the same wallet or a different wallet?

**Comment by bocheng0000** [comment]
The amount of ela in your wallet is your privacy. 
If you want someone to know the amount of ela that you own, you can give the person your addresses and sign a message to proof that you own the addresses.

The feature will be added in a later version.

**Comment by yz89** [comment]
@CooperLee123 He may use the web wallet https://wallet.elastos.org which is the HD wallet implement and will generate a different address for change automatically.
