### ISSUE TITLE
 Elastos seems to have 3 serious vulnerabilities. 

### ISSUE THREAD

**Issue by 0xMrcat** [elastos/Elastos.ELA#256]
I saw it [here](https://dvpnet.io/list/index/s/%E4%BA%A6%E6%9D%A5%E4%BA%91). It was dangerous.

**Comment by yz89** [comment]
Ok, got it. Thank you very much

**Comment by yz89** [comment]
Ok, got it. Thank you very much.

https://github.com/elastos/Elastos.ELA/pull/254 try to fix these problems.
