### ISSUE TITLE
Error running glide update

### ISSUE THREAD

**Issue by kpachhai** [elastos/Elastos.ELA#3]
I was wondering if anyone could help me with this. I just cloned the repo and was trying to do glide update but I get the following error:

kpachhai@kpubuntu:~/go/src/github.com/elastos/Elastos.ELA$ glide update
[WARN] The name listed in the config file (Elastos.ELA) does not match the current location (github.com/elastos/Elastos.ELA)
[INFO]  Downloading dependencies. Please wait...
[INFO]  --> Fetching github.com/golang/crypto
[INFO]  --> Fetching github.com/syndtr/goleveldb
[INFO]  --> Fetching github.com/itchyny/base58-go
[INFO]  --> Fetching github.com/gorilla/websocket
[INFO]  --> Fetching github.com/pborman/uuid
[INFO]  --> Fetching github.com/pebbe/zmq4
[INFO]  Resolving imports
[INFO]  --> Fetching Elastos.ELA/common
[WARN]  Unable to checkout Elastos.ELA/common
[ERROR] Error looking for Elastos.ELA/common: Cannot detect VCS
[WARN]  Unable to set version on Elastos.ELA/common to . Err: Cannot detect VCS
[WARN]  Unable to set version on Elastos.ELA/common to . Err: Cannot detect VCS
[WARN]  Unable to set version on Elastos.ELA/common to . Err: Cannot detect VCS
[INFO]  --> Fetching Elastos.ELA/consensus/pow
[WARN]  Unable to checkout Elastos.ELA/consensus/pow
[ERROR] Error looking for Elastos.ELA/consensus/pow: Cannot detect VCS
[INFO]  --> Fetching Elastos.ELA/core/ledger
[WARN]  Unable to checkout Elastos.ELA/core/ledger
[ERROR] Error looking for Elastos.ELA/core/ledger: Cannot detect VCS
[INFO]  --> Fetching Elastos.ELA/core/store
[WARN]  Unable to checkout Elastos.ELA/core/store
[ERROR] Error looking for Elastos.ELA/core/store/ChainStore: Cannot detect VCS
[WARN]  Unable to set version on Elastos.ELA/core/store to . Err: Cannot detect VCS
[INFO]  --> Fetching Elastos.ELA/core/transaction
[WARN]  Unable to checkout Elastos.ELA/core/transaction
[ERROR] Error looking for Elastos.ELA/core/transaction: Cannot detect VCS
[WARN]  Unable to set version on Elastos.ELA/core/transaction to . Err: Cannot detect VCS
[INFO]  --> Fetching Elastos.ELA/net/node
[WARN]  Unable to checkout Elastos.ELA/net/node
[ERROR] Error looking for Elastos.ELA/net/node: Cannot detect VCS
[INFO]  --> Fetching Elastos.ELA/net/protocol
[WARN]  Unable to checkout Elastos.ELA/net/protocol
[ERROR] Error looking for Elastos.ELA/net/protocol: Cannot detect VCS
[INFO]  --> Fetching Elastos.ELA/net/servers
[WARN]  Unable to checkout Elastos.ELA/net/servers
[ERROR] Error looking for Elastos.ELA/net/servers: Cannot detect VCS
[WARN]  Unable to set version on Elastos.ELA/net/servers to . Err: Cannot detect VCS
[WARN]  Unable to set version on Elastos.ELA/net/servers to . Err: Cannot detect VCS
[WARN]  Unable to set version on Elastos.ELA/net/servers to . Err: Cannot detect VCS
[WARN]  Unable to set version on Elastos.ELA/net/servers to . Err: Cannot detect VCS
[INFO]  --> Fetching Elastos.ELA/core/auxpow
[WARN]  Unable to checkout Elastos.ELA/core/auxpow
[ERROR] Error looking for Elastos.ELA/core/auxpow: Cannot detect VCS
[INFO]  --> Fetching Elastos.ELA/crypto
[WARN]  Unable to checkout Elastos.ELA/crypto
[ERROR] Error looking for Elastos.ELA/crypto: Cannot detect VCS
[INFO]  --> Fetching Elastos.ELA/events
[WARN]  Unable to checkout Elastos.ELA/events
[ERROR] Error looking for Elastos.ELA/events: Cannot detect VCS
[INFO]  --> Fetching Elastos.ELA/core/contract
[WARN]  Unable to checkout Elastos.ELA/core/contract
[ERROR] Error looking for Elastos.ELA/core/contract: Cannot detect VCS
[WARN]  Unable to set version on Elastos.ELA/core/contract to . Err: Cannot detect VCS
[INFO]  --> Fetching Elastos.ELA/core/asset
[WARN]  Unable to checkout Elastos.ELA/core/asset
[ERROR] Error looking for Elastos.ELA/core/asset: Cannot detect VCS
[INFO]  --> Fetching Elastos.ELA/core/signature
[WARN]  Unable to checkout Elastos.ELA/core/signature
[ERROR] Error looking for Elastos.ELA/core/signature: Cannot detect VCS
[INFO]  --> Fetching Elastos.ELA/errors
[WARN]  Unable to checkout Elastos.ELA/errors
[ERROR] Error looking for Elastos.ELA/errors: Cannot detect VCS
[WARN]  Unable to set version on Elastos.ELA/core/store to . Err: Cannot detect VCS
[INFO]  --> Fetching Elastos.ELA/core/code
[WARN]  Unable to checkout Elastos.ELA/core/code
[ERROR] Error looking for Elastos.ELA/core/code: Cannot detect VCS
[INFO]  --> Fetching Elastos.ELA/net/message
[WARN]  Unable to checkout Elastos.ELA/net/message
[ERROR] Error looking for Elastos.ELA/net/message: Cannot detect VCS
[ERROR] Error scanning Elastos.ELA/common/config: cannot find package "." in:
        /home/kpachhai/.glide/cache/src/https-Elastos.ELA-common/config
[ERROR] Error scanning Elastos.ELA/common/log: cannot find package "." in:
        /home/kpachhai/.glide/cache/src/https-Elastos.ELA-common/log
[ERROR] Error scanning Elastos.ELA/common/serialization: cannot find package "." in:
        /home/kpachhai/.glide/cache/src/https-Elastos.ELA-common/serialization
[ERROR] Error scanning Elastos.ELA/core/store/LevelDBStore: cannot find package "." in:
        /home/kpachhai/.glide/cache/src/https-Elastos.ELA-core-store/LevelDBStore
[ERROR] Error scanning Elastos.ELA/core/transaction/payload: cannot find package "." in:
        /home/kpachhai/.glide/cache/src/https-Elastos.ELA-core-transaction/payload
[ERROR] Error scanning Elastos.ELA/net/servers/httpjsonrpc: cannot find package "." in:
        /home/kpachhai/.glide/cache/src/https-Elastos.ELA-net-servers/httpjsonrpc
[ERROR] Error scanning Elastos.ELA/net/servers/httpnodeinfo: cannot find package "." in:
        /home/kpachhai/.glide/cache/src/https-Elastos.ELA-net-servers/httpnodeinfo
[ERROR] Error scanning Elastos.ELA/net/servers/httprestful: cannot find package "." in:
        /home/kpachhai/.glide/cache/src/https-Elastos.ELA-net-servers/httprestful
[ERROR] Error scanning Elastos.ELA/net/servers/httpwebsocket: cannot find package "." in:
        /home/kpachhai/.glide/cache/src/https-Elastos.ELA-net-servers/httpwebsocket
[ERROR] Error scanning Elastos.ELA/core/contract/program: cannot find package "." in:
        /home/kpachhai/.glide/cache/src/https-Elastos.ELA-core-contract/program
[ERROR] Error scanning Elastos.ELA/core/store: cannot find package "." in:
        /home/kpachhai/.glide/cache/src/https-Elastos.ELA-core-store
[INFO]  --> Fetching github.com/golang/snappy
[ERROR] Failed to retrieve a list of dependencies: Error resolving imports

**Comment by hejianhui** [comment]
Are you in Chinese mainland now?
This error may caused by the Great Fire Wall.
You can try a VPN to solve this.

**Comment by kpachhai** [comment]
I am located in the US

**Comment by hejianhui** [comment]
Maybe there's something wrong with your local environment.

[WARN] The name listed in the config file (Elastos.ELA) does not match the current location (github.com/elastos/Elastos.ELA)

I've never seen this warning before.
what does this warning mean? What's your project directory?

**Comment by kpachhai** [comment]
I am putting this in my $GOPATH which is ~/go

~/go/src/github.com/elastos/Elastos.ELA

**Comment by hejianhui** [comment]
Put it in your $GOPATH，not $GOPATH/github.com/elastos/

**Comment by kpachhai** [comment]
That solved the issue. That makes no sense to me though. Shouldn't it be under $GOPATH/src/github.com/elastos/? 

Oh well, got it working now though. Thanks for your help.
