### ISSUE TITLE
Getting error when making on Mac OS: cannot use nil as type _Ctype_CFDataRef in assignment

### ISSUE THREAD

**Issue by waynetogo** [elastos/Elastos.ELA#4]
Chiawens-iMac:Elastos.ela yang$ make
go build  -ldflags "-X ELA/common/config.Version=v0.0.1-5-ga7077-3-g1641"  -o node main.go
# vendor/crypto/x509
/usr/local/Cellar/go/1.10/libexec/src/vendor/crypto/x509/root_cgo_darwin.go:210: cannot use nil as type _Ctype_CFDataRef in assignment
/usr/local/Cellar/go/1.10/libexec/src/vendor/crypto/x509/root_cgo_darwin.go:211: cannot use nil as type _Ctype_CFDataRef in assignment
/usr/local/Cellar/go/1.10/libexec/src/vendor/crypto/x509/root_cgo_darwin.go:221: cannot convert nil to type _Ctype_CFDataRef
make: *** [all] Error 2
Chiawens-iMac:Elastos.ela yang$

**Comment by hejianhui** [comment]
did you ever run command 'glide update' and 'glide install'?

**Comment by waynetogo** [comment]
yep, with
`brew install glide go zeromq `

had to add a lot of packages to vender/golang.org, vender/golang_org, vender/github.com, vender/crypto to get to this point.

**Comment by hejianhui** [comment]
Are you using golang 1.10? We need golang with version 1.8 or later

**Comment by waynetogo** [comment]
yep with
`brew install go`

Warning: go 1.10 is already installed

I'll try to reinstall and see...

**Comment by waynetogo** [comment]
same error after installing golang from brew and the downloaded package:

```
go build  -ldflags "-X ELA/common/config.Version=v0.0.1-5-ga7077-3-g1641"  -o node main.go
# vendor/crypto/x509
../vendor/crypto/x509/root_cgo_darwin.go:210: cannot use nil as type _Ctype_CFDataRef in assignment
../vendor/crypto/x509/root_cgo_darwin.go:211: cannot use nil as type _Ctype_CFDataRef in assignment
../vendor/crypto/x509/root_cgo_darwin.go:221: cannot convert nil to type _Ctype_CFDataRef
make: *** [all] Error 2
```

**Comment by hejianhui** [comment]
so what's your golang version now?

**Comment by waynetogo** [comment]
Golang version 1.10

**Comment by hejianhui** [comment]
see this: https://github.com/google/certificate-transparency-go/issues/131 

may be some of help

**Comment by hejianhui** [comment]
# hejianhui @ hejianhui-macbook in ~ [15:07:26]
$ brew install go
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/go-1.9.1.high_sierra.bottle.tar.gz

you see, when I execute brew install go, homebrew install go 1.9.1 for me. So why go 1.10 was installed on your Mac when you executed brew? I've never seen this.

**Comment by yz89** [comment]
Look at this issue https://github.com/fsnotify/fsevents/issues/33
It may be caused by "go 1.10 + macOS High Sierra"

try go 1.9

**Comment by waynetogo** [comment]
Strange homebrew grabs 1.10 for me...

```
Chiawens-iMac:~ yang$   brew uninstall --ignore-dependencies go
Uninstalling /usr/local/Cellar/go/1.10... (8,150 files, 336.9MB)
go 1.8.3 1 is still installed.
Remove all versions with `brew uninstall --force go`.
Chiawens-iMac:~ yang$ brew install go
==> Downloading https://homebrew.bintray.com/bottles/go-1.10.sierra.bottle.tar.g
######################################################################## 100.0%
==> Pouring go-1.10.sierra.bottle.tar.gz
==> Caveats
A valid GOPATH is required to use the `go get` command.
If $GOPATH is not specified, $HOME/go will be used by default:
  https://golang.org/doc/code.html#GOPATH

You may wish to add the GOROOT-based install location to your PATH:
  export PATH=$PATH:/usr/local/opt/go/libexec/bin
==> Summary
🍺  /usr/local/Cellar/go/1.10: 8,150 files, 336.9MB
Chiawens-iMac:~ yang$ 
```

I'm building on Mac OS Sierra 10.12.6. I will try the older versions of Golang.

**Comment by waynetogo** [comment]
Worked on Mac OS 10.13.3 high Sierra.

**Comment by waynetogo** [comment]
Step 1. Install XCode and comman line tools. (“xcode-select --install”)
Step 2. Install homebrew. (/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)”, brew doctor, brew update)
Step 3. brew install glide go pkg-config zmq
Step 4. Go to folder in terminal “/usr/local/Cellar/go/1.10/libexec/src”
Step 5. Clone Elastos.ELA. (git clone https://github.com/elastos/Elastos.ELA.git)
Step 6. Clone golang/crypto. (cd /usr/local/Cellar/go/1.10/libexec/src/vendor, mkdir github.com, cd github.com, mkdir golang, cd golang, git clone https://github.com/golang/crypto.git)
Step 7. Clone gorilla/websocket. (cd /usr/local/Cellar/go/1.10/libexec/src/vendor/github.com, mkdir gorilla, cd gorilla, git clone https://github.com/gorilla/websocket.git)
Step 8. Clone itchyny/base58-go. (cd  /usr/local/Cellar/go/1.10/libexec/src/vendor/github.com/, mkdir itchyny, cd itchyny, git clone https://github.com/itchyny/base58-go.git)
Step 9. Clone pborman/uuid. (cd /usr/local/Cellar/go/1.10/libexec/src/vendor/github.com/, mkdir pborman, cd pborman, git clone https://github.com/pborman/uuid.git)
Step 10. Clone pebbe/zmq4. (cd /usr/local/Cellar/go/1.10/libexec/src/vendor/github.com/, mkdir pebbe, cd pebbe,  git clone https://github.com/pebbe/zmq4.git)
Step 11. Clone syndtr/goleveldb. (cd /usr/local/Cellar/go/1.10/libexec/src/vendor/github.com/, mkdir syndtr, cd syndtr, git clone https://github.com/syndtr/goleveldb.git)

Step 12. Clone golang/snappy. (Cd /usr/local/Cellar/go/1.10/libexec/src/vendor/github.com/golang/, git clone https://github.com/golang/snappy.git)

Step 13. Go to Elastos.ELA folder. (Cd /usr/local/Cellar/go/1.10/libexec/src/elastos.ela)

Step 14. Make
