### ISSUE TITLE
Can't access the number of votes until restart the node program

### ISSUE THREAD

**Issue by umbrellateng** [elastos/Elastos.ELA#459]
After the voting transaction is successfully sent, after acknowledging the two blocks, the node program must be restarted to access the number of votes through RPC service

**Comment by yz89** [comment]
fixed in #479

**Comment by umbrellateng** [comment]
Test pass， the bug has been fixed!
Now you don't need to restart the node program to see the information just voted through the RPC interface, you can see the vote information after two blocks has been confirmed.
