### ISSUE TITLE
After restarting the node, the previous registration voting information cannot be seen using the RPC interface

### ISSUE THREAD

**Issue by umbrellateng** [elastos/Elastos.ELA#503]
Information before restarting the node:

![image](https://user-images.githubusercontent.com/39583900/50439149-ef077d80-092b-11e9-994f-9a9c0dec8d3b.png)

Information after restarting the same node:

![image](https://user-images.githubusercontent.com/39583900/50439196-18c0a480-092c-11e9-8288-68916a6ffc3b.png)

**Comment by RainFallsSilent** [comment]
It's not a bug, it just needs to clear the previous error data because of new checks.

**Comment by umbrellateng** [comment]
Test pass, the bug has been fixed!
