### ISSUE TITLE
The main node program reports  "[CheckCancelProducerTransaction], Invalid producer" and can't continue to sync higher block! 

### ISSUE THREAD

**Issue by umbrellateng** [elastos/Elastos.ELA#512]
![image](https://user-images.githubusercontent.com/39583900/50500929-7ae5ea80-0a8f-11e9-8df7-720f94bc3eb4.png)

**Comment by RainFallsSilent** [comment]
It's not a bug, it just needs to clear the previous error data because of new checks.

**Comment by umbrellateng** [comment]
Ok, test pass!
