### ISSUE TITLE
Interface return format is not specified

### ISSUE THREAD

**Issue by modongjie** [elastos/Elastos.ELA#523]
sendrawtransaction:
{
    "Desc": "INTERNAL ERROR, ErrInvalidInput",
    "Error": 45003,
    "Result": "INTERNAL ERROR, ErrInvalidInput"
}

it should be：
{
    "error": {
        "code": 44001,
        "id": null,
        "message": "cannot find transaction in blockchain and transactionpool"
    },
    "jsonrpc": "2.0",
    "result": null
}

**Comment by modongjie** [comment]
returnDepositcoinTx:
log: [CheckReturnDepositCoinTransaction], no cancel sign found on this public key
interface rpc retrun:
{
    "Desc": "",
    "Error": 45021,
    "Result": ""
}

**Comment by modongjie** [comment]
Check that all restful and RPC interfaces return results correctly and return results incorrectly

**Comment by RainFallsSilent** [comment]
tested the sendrawtransaction interface and found no problem
{
    "error": {
        "code": 45010,
        "id": null,
        "message": "INTERNAL ERROR, ErrDoubleSpend"
    },
    "jsonrpc": "2.0",
    "result": null
}

**Comment by modongjie** [comment]
after register producer ，returnProducer error info:
rpc:
{
    "error": {
        "code": 45021,
        "id": null,
        "message": ""
    },
    "jsonrpc": "2.0",
    "result": null
}

log:
[CheckReturnDepositCoinTransaction], no cancel sign found on this public key

**Comment by modongjie** [comment]
verified
