### ISSUE TITLE
Start node has no version number

### ISSUE THREAD

**Issue by modongjie** [elastos/Elastos.ELA#527]
branch :release_v0.2.2
commit :039168a1176ec6f26a75a6e24c773c5b0dde01d0

2019/01/03 16:34:39.325272 [INF] GID 1, Node version:  
2019/01/03 16:34:39.325591 [INF] GID 1, BlockChain init

**Comment by yz89** [comment]
fixed in #553

**Comment by modongjie** [comment]
Verified
