### ISSUE TITLE
richest-list balance is incorrect

### ISSUE THREAD

**Issue by treevong** [elastos/Elastos.ELA#67]
Sum up balance of top100 addresses is already exceed total supply.
https://blockchain.elastos.org/addrs/richest-list

**Comment by treevong** [comment]
@kevingzhang not sure if you can help?

Here are few examples. Balance of addresses at rank 7-8-9-10 in the richest list not match with 'Final Balance' of each address.

https://blockchain.elastos.org/address/EcrgQEq5ATuTxSoGFZD4U3wobk9jxPF61v
https://blockchain.elastos.org/address/EQMzzwbn6eg8QXv8PyoZjwWNjfDkmEtoeG
https://blockchain.elastos.org/address/EZwR6sZiBR4johpju4sbi6NoZZH4AVzZaq
https://blockchain.elastos.org/address/EZohSqqPzKnxQ7GxyGk9HZsAjcTQvs8GKR

**Comment by kpachhai** [comment]
@treevong ELA has an inflation of 4% per year so the total supply will keep on growing. So, the total supply is already over 33 million at the moment. This inflation is what will be used to reward miners.

**Comment by treevong** [comment]
I understand about the inflation. I have no problem on that.

Please check the addresses I mentioned above as an example. Balance between richest list and each individual addess are not match.

**Comment by bocheng0000** [comment]
@treevong The richest-list has been updated and the bug is fixed. Please check it again.

The balance in the list will be a few blocks later than the real-time balance.

**Comment by treevong** [comment]
It's good now. Thank you.
