### ISSUE TITLE
how to connect to mainnet

### ISSUE THREAD

**Issue by bitcodernull** [elastos/Elastos.ELA#68]
thanks

**Comment by hejianhui** [comment]
Our main net will be open to public in 2019 after sufficient testing and developing. You cannot connect to our mainnet by now. Sorry.

**Comment by yz89** [comment]
In addition to mining, you can connect to the mainnet and sync blocks now.

https://github.com/elastos/Elastos.ELA/blob/master/docs/Exchange_Docking_Reference.md
