### ISSUE TITLE
RPC interface "getconfirmbyheight" and "getconfirmbyhash" return wrong blockhash 

### ISSUE THREAD

**Issue by liteng0313** [elastos/Elastos.ELA#760]
![image](https://user-images.githubusercontent.com/39583900/54337696-9c0baf80-466a-11e9-83ba-dd18130b49ec.png)

**Comment by RainFallsSilent** [comment]
fixed in #761

**Comment by liteng0313** [comment]
Test Pass, the bug has been fixed!
